import type { NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { useStore } from "../helpers/useStore";

interface FormState {
  username: string;
}

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FormState>();
  const { setUsername } = useStore();
  const router = useRouter();

  return (
    <form
      onSubmit={handleSubmit(({ username }) => {
        setUsername(username);
        router.push("/test-chatroom");
      })}
    >
      <div className="flex items-center justify-center w-full h-screen bg-white">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="w-[75%] max-w-[300px] h-[45%] px-4 py-8 rounded-md bg-gray-300 flex flex-col justify-between items-center">
          <h4 className="m-0 font-bold font-quicksand">ChatApp</h4>
          <div className="flex flex-col items-center justify-center w-full gap-2">
            <h1 className="m-0 text-lg font-bold text-center font-merriweather">
              Welcome!
            </h1>
            <p className="m-0 italic capitalize font-quicksand">
              please enter a username
            </p>
          </div>
          <div className="w-full min-h-[75px]">
            <input
              autoComplete="off"
              className={
                errors.username
                  ? "border w-full p-1 outline-none rounded-sm focus-within:ring transition-all duration-200 ring ring-red-500"
                  : "border w-full p-1 outline-none rounded-sm focus-within:ring transition-all duration-200"
              }
              {...register("username", { required: "Username is required..." })}
              type="text"
            />
            {errors.username && (
              <p className="mt-2 text-xs text-red-500 uppercase">
                {errors.username.message}
              </p>
            )}
          </div>
          <button className="w-full py-3 tracking-wider text-white capitalize bg-black rounded font-roboto hover:bg-slate-800 active:bg-slate-900">
            ENTER
          </button>
        </main>
      </div>
    </form>
  );
};

export default Home;
